baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'UI/UX Design Links'
theme = 'PaperMod'

[params]
  description = "A collection of software, web, and desktop environment user interface design links."
  defaultTheme = "auto"

  [params.assets]
    disableHLJS = true
